#!/bin/sh
dropdb boostcon.db
createdb boostcon.db 
    
if (uname -a | grep -q ' boost-consulting.com'); then
    BOOSTCON_SITE_CONTEXT=boostcon
    export BOOSTCON_SITE_CONTEXT
    cd /usr/local/www/apache22/boostcon/src/boost_consulting;
else 
    cd ~/src/boostcon/site/boost_consulting;
fi;

python manage.py syncdb << EOF
no
EOF

python manage.py shell --plain << EOF
import conference.populate
EOF

